  
services:
  orchestrator:
    tty: true
    build:
      context: .
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        PORT: ${PORT}
    container_name: rust_orchestrator
    ports:
      - "3000:3000"
    env_file: .env
    networks:
      default:
        ipv4_address: 172.16.0.25
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3300/health"]
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 15s

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      default:
        ipv4_address: 172.16.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: mongod --port ${MONGO_PORT:-27017}
    volumes:
      - mongo-config:/data/configdb
      - mongo-db:/data/db

volumes:
  mongo-config:
  mongo-db:

networks:
  default:
    name: wasmiot-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24